### ISSUE TITLE
Build failure with this Widget

### ISSUE THREAD

**Issue by ghost** [CaffeinaLab/Ti.FormBuilder#1]
Hi Guys

I'm trying to build a project with your widget and I'm getting the following error:

```
"Ti.FormBuilder: you need to install Trimethyl to use this widget."
```

Any ideas as to how to fix this issue?

Thanks in advance

**Comment by ghost** [comment]
Just seen the Module you've built

**Comment by kopiro** [comment]
Did you solved?

**Comment by yozef** [comment]
Wonder how you solved this, I'm still getting: Ti.FormBuilder: you need to install Trimethyl to use this widget.

**Comment by Jei** [comment]
@yozef You may have to install Trimethyl to use the widget.
https://github.com/trimethyl/trimethyl
